# Задаем имя проекта
name: starburger-docker
# Перечень сервисов
services:

  # Определяем имя сервиса для базы данных
  postgres_database:
    # Определяем образ для запуска базы данных
    image: postgres:16-alpine
    # Задаем переменные окружения для создания базы данных из env файла
    env_file:
      - backend/.env
    # Создаем том для хранения базы данных postgres
    volumes:
      - ./postgres_database:/var/lib/postgresql/data
    # Пробрасываем сетевой порт из контейнера на компьютер.
    ports:
      - "127.0.0.1:5432:5432"
    # Проверка подключения к БД
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h localhost -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  # Определяем имя,которое будет присвоено образу frontendа
  frontend:
    # Указываем имя образа которое будет иметь сервис
    image: frontend:latest
    # Указываем Docker Compose, что образ нужно собрать локально перед запуском сервиса.
    build:
      # Определяеv путь к каталогу сборки
      context: ./frontend
      # Указываем имя файла инструкций Docker (Dockerfile) внутри каталога context.
      dockerfile: Dockerfile
    # Определяет монтирование локальных директорий операционной системы внутрь файловой системы контейнера
    volumes:
      - ./frontend/bundles-src:/frontend/bundles-src
      - ./frontend/bundles:/frontend/bundles
    # Запускаем команду сборки фронтенда в контейнере
    command: ./node_modules/.bin/parcel watch bundles-src/index.js --dist-dir /frontend/bundles --public-url="./"
  
  
  # Определяем имя сервиса backend-migrate
  backend-migrate:
    # Указываем имя образа которое будет иметь сервис
    image: backend-migrate:latest
    # Указываем docker compose, что образ нужно собрать локально перед запуском сервиса
    build:
      # Определяем путь к какталогу сборки
      context: ./backend
      # Указываем имя файла инструкций Docker (Dockerfile) внутри каталога context
      dockerfile: Dockerfile
      # Указываем целевой образ миграции
      target: backend_migrate
    # Определяем env файл для безопасного хранения настроек
    env_file:
      - ./backend/.env
    # Определяем монтирование локальныйх директорий операционной системы внутрь файловой системы контейнера
    volumes:
      - ./backend:/backend:rw
    # Устанавливаем зависимость от контейнера базы данных
    depends_on:
      postgres_database:
        # Говорим что нужно запускать только после того как пройдет проверка работоспособности БД
        condition: service_healthy
    # Говорим что не нужно перезапускать после миграций
    restart: "no"

  # Определяем имя сервиса backend
  backend:
    # Указываем Docker Compose, что образ нужно собрать локально перед запуском сервиса.
    build:
      # Определяеv путь к каталогу сборки
      context: ./backend
      # Указываем имя файла инструкций Docker (Dockerfile) внутри каталога context.
      dockerfile: Dockerfile
      # Указываем целевой образ бэкенда
      target: backend
    # Определяем env файл для безопасного хранения настроек
    env_file:
      - ./backend/.env
    # Определяет монтирование локальных директорий операционной системы внутрь файловой системы контейнера
    volumes:
      - ./backend:/backend:rw
      - ./frontend:/frontend:rw
      - ./media:/media:rw
    # Пробрасываем сетевой порт из контейнера на компьютер.
    ports:
      - "127.0.0.1:8000:8000"
    # Запускаем backend внутри контейнера на порту 0.0.0.0:8000
    command: gunicorn -w 3 -b 0.0.0.0:8000 star_burger.wsgi:application
    # Устанавливаем зависимость запуска backend после frontend
    depends_on:
      - postgres_database
      - frontend
      - backend-migrate
volumes:
  postgres_database:







