# Задаем имя проекта
name: starburger-docker
# Перечень сервисов
services:
  # Определяем имя,которое будет присвоено образу frontendа
  frontend:
    # Указываем имя образа которое будет иметь сервис
    image: frontend:latest
    # Указываем Docker Compose, что образ нужно собрать локально перед запуском сервиса.
    build:
      # Определяеv путь к каталогу сборки
      context: ./frontend
      # Указываем имя файла инструкций Docker (Dockerfile) внутри каталога context.
      dockerfile: Dockerfile
    # Определяет монтирование локальных директорий операционной системы внутрь файловой системы контейнера
    volumes:
      - ./frontend/bundles-src:/frontend/bundles-src
      - ./frontend/bundles:/frontend/bundles
    # Запускаем команду сборки фронтенда в контейнере
    command: ./node_modules/.bin/parcel watch bundles-src/index.js --dist-dir /frontend/bundles --public-url="./"
  
  # Определяем имя сервиса backend
  backend:
    # Указываем Docker Compose, что образ нужно собрать локально перед запуском сервиса.
    build:
      # Определяеv путь к каталогу сборки
      context: ./backend
      # Указываем имя файла инструкций Docker (Dockerfile) внутри каталога context.
      dockerfile: Dockerfile
    # Определяем env файл для безопасного хранения настроек
    env_file:
      - ./backend/.env
    # Определяет монтирование локальных директорий операционной системы внутрь файловой системы контейнера
    volumes:
      - ./backend:/backend:rw
      - ./frontend:/frontend:rw
      - ./media:/media:rw
    # Пробрасываем сетевой порт из контейнера на компьютер.
    ports:
      - "127.0.0.1:8000:8000"
    # Запускаем backend внутри контейнера на порту 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    # Устанавливаем зависимость запуска backend после frontend
    depends_on:
      - frontend







